export { default as CheckMark } from "./checkMark.svg";
export { default as Logo } from "./Logo.svg";
export { default as Boy } from "./Boy.svg";
export { default as Girl } from "./Girl.svg";
export { default as Man } from "./Man.svg";
export { default as Woman } from "./Woman.svg";
export { default as Check } from "./Check.svg";
export * from "./chat";
export * from "./calendar";
export * from "./my";
export { default as Alarm } from "./alarm.svg";
export { default as Goal } from "./goal.svg";
export { default as Plus } from "./Plus.svg";
export { default as LeftArrow } from "./LeftArrow.svg";
export { default as Todo } from "./Todo.svg";
export { default as TodoActive } from "./TodoActive.svg";
